export const ActionTypes = {
  FETCH_USERDATA_LOADING: "FETCH_USERDATA_LOADING",
  FETCH_USERDATA_SUCCESS: "FETCH_USERDATA_SUCCESS",
  FETCH_USERDATA_FAILURE: "FETCH_USERDATA_FAILURE",
  ADD_USERDATA_SUCCESS: "ADD_USERDATA_SUCCESS",
  ADD_USERDATA_FAILURE: "ADD_USERDATA_FAILURE",

  FETCH_COUNTRIES_LOADING: "FETCH_COUNTRIES_LOADING",
  FETCH_COUNTRIES_SUCCESS: "FETCH_COUNTRIES_SUCCESS",
  FETCH_COUNTRIES_FAILURE: "FETCH_COUNTRIES_FAILURE",

  FETCH_STATES_LOADING: "FETCH_STATES_LOADING",
  FETCH_STATES_SUCCESS: "FETCH_STATES_SUCCESS",
  FETCH_STATES_FAILURE: "FETCH_STATES_FAILURE",

  FETCH_TODOS_LOADING: "FETCH_TODOS_LOADING",
  FETCH_TODOS_SUCCESS: "FETCH_TODOS_SUCCESS",
  FETCH_TODOS_FAILURE: "FETCH_TODOS_FAILURE",
};
