export const ActionTypes ={
    FETCH_USERDATA_LOADING:"FETCH_USERDATA_LOADING",
    FETCH_USERDATA_SUCCESS:"FETCH_USERDATA_SUCCESS",
    FETCH_USERDATA_FAILURE:"FETCH_USERDATA_FAILURE",
    ADD_USERDATA_SUCCESS:"ADD_USERDATA_SUCCESS",
    ADD_USERDATA_FAILURE:"ADD_USERDATA_FAILURE"
}